import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { AppSettings } from "../appSettings";
import { catchError, map } from "rxjs/operators";
import { Observable, throwError } from "rxjs";
import { RefItem } from "../_models/filters";
import { RefserviceService } from "./refservice.service";

@Injectable({
  providedIn: "root",
})
export class FakeviewService {
  t_json: string="";
  t_object: Object[];

  constructor() {
    const t_json = [
      {
        code: "house_number",
        name: "PSPH_Number",
        type: "string",
        caption: "Номер дома",
        size: "5",
      },
      {
        code: "house_block",
        name: "PSPH_Building",
        type: "string",
        caption: "Корпус",
        size: "5",
      },
      {
        code: "house_letter",
        name: "PSPH_Letter",
        type: "string",
        caption: "Литера",
        size: "45",
      },
      // {
      //     'code': 'psph_ouidname',
      //     'name': 'PSPH_OUIDNAME',
      //     'type': 'string',
      //     'caption': 'Полное наименование управляющей компании',
      //     'size': '5'
      // },
      {
        code: "management_org_id",
        name: "management_org_id",
        type: "int",
        caption: "Управляющая организация",
        showAs: "select",
        fieldoptions: [],
      },
      {
        code: "private_date",
        name: "PSPH_PrivateNumber",
        type: "datetime",
        caption: "Дата приватизации первого помещения",
        size: "5",
      },
      {
        code: "create_date",
        name: "PSPH_CreationDate",
        type: "datetime",
        caption: "Дата создания паспорта",
        size: "5",
      },
      {
        code: "inventory_number",
        name: "PSPH_InventoryNumber",
        type: "string",
        caption: "Инвентарный номер",
      },
      {
        code: "inventory_date",
        name: "PSPH_InventoryDate",
        type: "datetime",
        caption: "Дата инвентаризации",
      },
      {
        code: "registry_number",
        name: "PSPH_RegistryNumber",
        type: "string",
        caption: "Реестровый номер",
      },
      {
        code: "registry_date",
        name: "PSPH_RegistryDate",
        type: "datetime",
        caption: "Дата занесения в реестр",
      },
      {
        code: "cadastre_number",
        name: "PSPH_CadastreNumber",
        type: "string",
        caption: "Кадастровый номер",
      },
      {
        code: "cadastre_date",
        name: "PSPH_CadastreDate",
        type: "datetime",
        caption: "Дата занесения в кадастр",
      },
      {
        code: "failure_state",
        name: "PSPH_FailureState",
        type: "int",
        caption: "Аварийность",
        showAs: "check",
      },
      {
        code: "cultural_object_sign",
        name: "PSPH_Culture",
        type: "int",
        caption: "Объект культурного наследия",
        showAs: "check",
      },
      {
        code: "notes",
        name: "PSPH_Notes",
        type: "string",
        caption: "Примечания",
        showAs: "textarea",
      },
      {
        code: "archive",
        name: "PSPH_Archive",
        type: "int",
        caption: "Архив МКД",
        showAs: "check",
      },
      {
        code: "house_series",
        name: "PSPHA_Series",
        type: "string",
        caption: "Серия, тип проекта",
        size: "30",
      },
      {
        code: "living_building_area_privately_owned",
        name: "PSPHA_living_building_area_privately_owned",
        type: "float",
        caption: "В частной собственности",
      },
      {
        code: "living_building_area_state_owned",
        name: "PSPHA_living_building_area_state_owned",
        type: "float",
        caption: "В государственной собственности",
      },
      {
        code: "nlba_privately_owned",
        name: "PSPHA_nlba_privately_owned",
        type: "float",
        caption: "В частной собственности",
      },
      {
        code: "nlba_state_owned",
        name: "PSPHA_nlba_state_owned",
        type: "float",
        caption: "В государственной собственности",
      },
      {
        code: "build_year",
        name: "PSPHA_BuildingDate",
        type: "string",
        caption: "Год постройки",
        size: "5",
      },
      {
        code: "reconstruction_year",
        name: "PSPHA_ReconstructionDate",
        type: "string",
        caption: "Год проведения реконструкции",
        size: "5",
      },
      {
        code: "total_building_volume",
        name: "PSPHA_BuildingVolume",
        type: "float",
        caption: "Общий строительный объем",
        unit: "куб.м.",
      },
      {
        code: "stairway_count",
        name: "PSPHA_Stairs",
        type: "int",
        caption: "Число лестниц",
      },
      {
        code: "floor_count",
        name: "PSPHA_Storeys",
        type: "int",
        caption: "Число этажей",
      },
      {
        code: "category_id",
        name: "PSPH_BuildingCategory",
        type: "int",
        caption: "Категория",
        showAs: "select",
        fieldoptions: [
          {
            value: 0,
            display: "Не задано",
          },
          {
            value: 1,
            display: "Дореволюционной постройки, прошедшие капитальный ремонт",
          },
          {
            value: 2,
            display:
              "Дореволюционной постройки, не прошедшие капитальный ремонт",
          },
          {
            value: 3,
            display: "«Конструктивизм», постройки 1918-1930 г.г.",
          },
          {
            value: 4,
            display: "«Сталинские», постройки 1931-1956 г.г.",
          },
          {
            value: 5,
            display: "«Хрущевки» кирпичные, постройки 1957-1970 г.г.",
          },
          {
            value: 6,
            display: "«Хрущевки» панельные, постройки 1957-1970 г.г.",
          },
          {
            value: 7,
            display: "Кирпичные, постройки 1970-1980 г.г.",
          },
          {
            value: 8,
            display: "Панельные, постройки 1970-1980 г.г.",
          },
          {
            value: 9,
            display: "Кирпичные «Новое строительство», постройки после 1980 г.",
          },
          {
            value: 10,
            display: "Панельные «Новое строительство», постройки после 1980 г.",
          },
          {
            value: 11,
            display: "Деревянные дома",
          },
          {
            value: 12,
            display: "«Немецкие», постройки 1945-1948 г.г.",
          },
          {
            value: 13,
            display:
              'Дома, построенные после 1999 года, категории "Новое строительство кирпичные"',
          },
          {
            value: 14,
            display:
              'Дома, построенные после 1999 года, категории "Новое строительство панельные"',
          },
          {
            value: 15,
            display:
              "Дома нового строительства, построенные после 1980 года, с наружными многослойными и (или) оштукатуренными ограждающими конструкциями (за исключением домов, ограждающие конструкции которых выполнены из панелей, и домов с вентилируемыми фасадами)",
          },
          {
            value: 16,
            display:
              "Дома нового строительства, построенные после 1980 года, с вентилируемыми фасадами",
          },
        ],
      },
      {
        code: "residents_count",
        name: "PSPH_ResidentsCount",
        type: "int",
        caption: "Количество проживающих",
      },
      {
        code: "personal_account_count",
        name: "PSPH_PersonalAccountCount",
        type: "int",
        caption: "Число лицевых счетов",
      },
      {
        code: "mansard_area",
        name: "PSPHA_MansardArea",
        type: "float",
        caption: "Мансарды",
        unit: "кв.м.",
      },
      {
        code: "total_building_area",
        name: "PSPHA_BuildingArea",
        type: "float",
        caption: "Общая площадь дома",
        showAs: "display",
        unit: "кв.м.",
      },
      {
        code: "living_building_area",
        name: "PSPHA_BuildingAreaLiving",
        type: "float",
        caption: "Площадь жилых помещений",
        unit: "кв.м.",
      },
      {
        code: "non_living_building_area",
        name: "PSPHA_BuildingAreaNonLiving",
        type: "float",
        caption: "Площадь нежилых помещений функционального назначения",
        unit: "кв.м.",
      },
      {
        code: "hostel_room_count",
        name: "PSPHA_AppartmentsHostelRooms",
        type: "int",
        caption: "Количество комнат в общежитии",
        unit: "шт.",
      },
      {
        code: "hostel_total_area",
        name: "PSPHA_AppartmentsHostelArea",
        type: "float",
        caption: "Общая площадь общежитий",
        unit: "кв.м.",
      },
      {
        code: "hostel_living_area",
        name: "PSPHA_AppartmentsHostelLivingArea",
        type: "float",
        caption: "Жилая площадь общежитий",
        unit: "кв.м.",
      },
      {
        code: "non_living_room_count",
        name: "PSPHA_AppartmentsBuiltinUninhabitedCount",
        type: "int",
        caption: "Количество встроенных нежилых помещений",
        unit: "шт.",
      },
      {
        code: "non_living_room_total_area",
        name: "PSPHA_AppartmentsBuiltinUninhabitedArea",
        type: "float",
        caption: "Общая площадь встроенных нежилых помещений",
        unit: "кв.м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningStairs",
        type: "float",
        caption: "Уборочная площадь лестничных маршей и площадок",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningCorridors",
        type: "float",
        caption: "Уборочная площадь коридоров мест общего пользования",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningServiceTotal",
        type: "float",
        caption: "Всего",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningServiceOffice",
        type: "float",
        caption: "Офисные помещения",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningServiceConcierge",
        type: "float",
        caption: "Красные уголки, клубы, детские комнаты",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningServiceWorkshops",
        type: "float",
        caption:
          "Технические помещения (теплоцентры, водомерные узлы,электрощитовые, мусороприемные камеры и т.п.)",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningServiceOther",
        type: "float",
        caption: "Прочие",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundTotal",
        type: "float",
        caption: "Всего",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundLawn",
        type: "float",
        caption: "Газоны",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC1Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC1Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC1Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC2Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC2Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC2Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC3Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC3Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundICC3Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC1Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC1Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC1Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC2Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC2Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC2Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC3Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC3Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUICC3Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC1Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC1Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC1Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC2Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC2Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC2Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC3Total",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC3Mech",
        type: "float",
        caption: "Механизир.",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_CleaningGroundUCC3Hand",
        type: "float",
        caption: "Ручная",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundDocumented",
        type: "float",
        caption: "Общая площадь земельного участка по документам",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundTotal",
        type: "float",
        caption: "Всего",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundBuilton",
        type: "float",
        caption: "Застроенная площадь",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundNotBuilton",
        type: "float",
        caption: "Всего",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundHardsurfaceTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundHardsurfacePassage",
        type: "float",
        caption: "Проезды",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundHardsurfacePavement",
        type: "float",
        caption: "Тротуары",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundHardsurfaceOther",
        type: "float",
        caption: "Прочие",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundPlaygroundsTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundPlaygroundsChildish",
        type: "float",
        caption: "Детские",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundPlaygroundsSport",
        type: "float",
        caption: "Спортивные",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundPlaygroundsOther",
        type: "float",
        caption: "Прочие",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundGreenTotal",
        type: "float",
        caption: "Всего",
        showAs: "display",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundGreenSquare",
        type: "float",
        caption: "Сквер",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundGreenTreelawn",
        type: "float",
        caption: "Газон с деревьями",
        unit: "кв. м.",
      },
      {
        code: "",
        name: "PSPHAr_GroundGreenFlowerbed",
        type: "float",
        caption: "Газон, цветники, и т.п.",
        unit: "кв. м.",
      },
      {
        code: "heating_type",
        name: "PSPHE_Heating",
        type: "string",
        caption: "Тип отопления",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Центральное",
            display: "Центральное",
          },
          {
            value: "Автономная котельная",
            display: "Автономная котельная",
          },
          {
            value: "Печное",
            display: "Печное",
          },
          {
            value: "Квартальная котельная",
            display: "Квартальная котельная",
          },
          {
            value: "Индивидуальное",
            display: "Индивидуальное",
          },
        ],
      },
      {
        code: "cold_water",
        name: "PSPHE_ColdWater",
        type: "int",
        caption: "Холодное водоснабжение и канализация",
        showAs: "check",
      },
      {
        code: "stove_type",
        name: "PSPHE_StoveType",
        type: "string",
        caption: "Тип кухонной плиты",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Электроплита",
            display: "Электроплита",
          },
          {
            value: "Газовая плита",
            display: "Газовая плита",
          },
        ],
      },
      {
        code: "hot_water_type",
        name: "PSPHE_HotWater",
        type: "string",
        caption: "Тип горячего водоснабжения",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Центральное",
            display: "Центральное",
          },
          {
            value: "От газовых колонок",
            display: "От газовых колонок",
          },
          {
            value: "От дровяных колонок",
            display: "От дровяных колонок",
          },
          {
            value: "Бойлер",
            display: "Бойлер",
          },
        ],
      },
      {
        code: "electric_supply_type",
        name: "PSPHE_ElectricSupply",
        type: "string",
        caption: "Тип электроснабжения",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Центральное",
            display: "Центральное",
          },
        ],
      },
      {
        code: "gas_supply_type",
        name: "PSPHE_GasSupply",
        type: "string",
        caption: "Тип газоснабжения",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Центральное",
            display: "Центральное",
          },
          {
            value: "Нецентральное",
            display: "Нецентральное",
          },
        ],
      },
      {
        code: "gas_pipe_laying_type",
        name: "PSPHE_Gastype",
        type: "string",
        caption: "Способ прокладки сетей газоснабжения",
        showAs: "select",
        fieldoptions: [
          {
            value: "",
            display: "Не задано",
          },
          {
            value: "Открытый",
            display: "Открытый",
          },
          {
            value: "Закрытый",
            display: "Закрытый",
          },
        ],
      },
      {
        code: "ventilation",
        name: "PSPHE_Ventilation",
        type: "int",
        caption: "Вентиляция",
        showAs: "check",
      },
      {
        code: "internal_drainage",
        name: "PSPHE_InternalDrainage",
        type: "int",
        caption: "Внутренние водостоки",
        showAs: "check",
      },
      {
        code: "external_drainage",
        name: "PSPHE_ExternalDrainage",
        type: "int",
        caption: "Наружные водостоки",
        showAs: "check",
      },
      {
        code: "refuse_chute_count",
        name: "PSPHE_RefuseChute",
        type: "int",
        caption: "Мусоропроводы",
        showAs: "check",
      },
      {
        code: "lift_count",
        name: "PSPHE_LiftCount",
        type: "int",
        caption: "Лифты всего",
        unit: "шт.",
      },
      {
        code: "lift_sliding_door_count",
        name: "PSPHE_LiftWithSlidingDoorsCount",
        type: "int",
        caption: "в т.ч. с раздвижными дверями",
        unit: "шт.",
      },
      {
        code: "lift_opening_door_count",
        name: "PSPHE_LiftWithOpeningDoorsCount",
        type: "int",
        caption: "в т.ч. с открывающими дверями",
        unit: "шт.",
      },
      {
        code: "pzu_lock_count",
        name: "PSPHE_PZULock",
        type: "int",
        caption: "ПЗУ (переговорно-замочное устройство)",
        unit: "шт.",
      },
      {
        code: "code_lock_count",
        name: "PSPHE_CodedLock",
        type: "int",
        caption: "Кодовый замок",
        unit: "шт.",
      },
      {
        code: "fire_defence",
        name: "PSPHE_FireDefence",
        type: "int",
        caption: "АППЗ (система автоматической противопожарной защиты дома)",
        showAs: "check",
      },
      {
        code: "dispatching_systems",
        name: "PSPHE_DispatchingSystems",
        type: "int",
        caption: "Объединенные диспетчерские системы",
        showAs: "check",
      },
      {
        code: "telephone",
        name: "PSPHE_Telephone",
        type: "int",
        caption: "Телефон (общедомовые распределительные сети и устройства)",
        showAs: "check",
      },
      {
        code: "radio",
        name: "PSPHE_Radio",
        type: "int",
        caption: "Радио (общедомовые распределительные сети и устройства)",
        showAs: "check",
      },
      {
        code: "antenna",
        name: "PSPHE_Antenna",
        type: "int",
        caption: "Антенны коллективного пользования",
        showAs: "check",
      },
      {
        code: "cable_tv",
        name: "PSPHE_CableCasting",
        type: "int",
        caption: "Кабельное ТВ",
        showAs: "check",
      },
      {
        code: "disabled_people_lifts_count",
        name: "PSPHE_DisabledPeopleLiftsCount",
        type: "int",
        caption: "Количество подъемников для инвалидов",
        unit: "шт.",
      },
      {
        code: "basement_socle",
        name: "PSPHC1_BasementSocle",
        type: "float",
        caption: "Площадь цоколя",
        unit: "кв.м.",
      },
      {
        code: "basement_blind_area",
        name: "PSPHC1_BasementBlindarea",
        type: "float",
        caption: "Площадь отмостки",
        unit: "кв.м.",
      },
      {
        code: "basement_volume",
        name: "PSPHC1_BasementVolume",
        type: "float",
        caption: "Объем фундамента",
        unit: "куб.м.",
      },
      {
        code: "walls_area",
        name: "PSPHC1_WallsArea",
        type: "float",
        caption: "Площадь наружных стен",
        unit: "кв.м.",
      },
      {
        code: "walls_partition_area",
        name: "PSPHC1_WallsPartitionArea",
        type: "float",
        caption: "Площадь внутренних стен и перегородок",
        unit: "кв.м.",
      },
      {
        code: "inserted_floor_area",
        name: "PSPHC1_InsertedFloorFloorsArea",
        type: "float",
        caption: "Площадь междуэтажных",
        unit: "кв.м.",
      },
      {
        code: "inserted_floor_cellar_area",
        name: "PSPHC1_InsertedFloorsCellarArea",
        type: "float",
        caption: "Площадь подвальных",
        unit: "кв.м.",
      },
      {
        code: "inserted_floor_garret_area",
        name: "PSPHC1_InsertedFloorsGarretArea",
        type: "float",
        caption: "Площадь чердачных",
        unit: "кв.м.",
      },
      {
        code: "stairway_floor_area",
        name: "PSPHC1_FloorsStairwellArea",
        type: "float",
        caption: "Площадь цементных полов на лестничных клетках",
        unit: "кв.м.",
      },
      {
        code: "stairway_woodfloor_area",
        name: "PSPHC1_FloorsWoodStairwellArea",
        type: "float",
        caption: "Площадь деревянных полов на лестничных клетках",
        unit: "кв.м.",
      },
      {
        code: "pvc_tile_floor_area",
        name: "PSPHC1_FloorsPVCTileArea",
        type: "float",
        caption: "Площадь плитки ПХВ на л/к",
        unit: "кв.м.",
      },
      {
        code: "ceramic_tile_floor_area",
        name: "PSPHC1_FloorsCeramicTileArea",
        type: "float",
        caption: "Площадь полов из керамической плитки",
        unit: "кв.м.",
      },
      {
        code: "granite_floor_area",
        name: "PSPHC1_FloorsGraniteArea",
        type: "float",
        caption: "Площадь полов гранитных, мраморных",
        unit: "кв.м.",
      },
      {
        code: "heat_center_floor_area",
        name: "PSPHC1_FloorsHeatCenterArea",
        type: "float",
        caption:
          "Площадь цементных полов в теплоцентрах, водомерных узлах и щитовых",
        unit: "кв.м.",
      },
      {
        code: "garbage_room_floor_area",
        name: "PSPHC1_FloorsDumpArea",
        type: "float",
        caption: "Площадь цементных полов в мусоросборных камерах",
        unit: "кв.м.",
      },
      {
        code: "pit_floor_area",
        name: "PSPHC1_FloorsPitArea",
        type: "float",
        caption: "Площадь цементных полов в приямках",
        unit: "кв.м.",
      },
      {
        code: "engine_room_floor_area",
        name: "PSPHC1_FloorsEngineRoomArea",
        type: "float",
        caption: "Площадь цементных полов в машинных отделениях",
        unit: "кв.м.",
      },
      {
        code: "linoleum_floor_area",
        name: "PSPHC1_FloorsLinoleumArea",
        type: "float",
        caption: "Площадь полов с покрытием из линолеума",
        unit: "кв.м.",
      },
      {
        code: "parquet_floor_area",
        name: "PSPHC1_FloorsParquetArea",
        type: "float",
        caption: "Площадь паркетных полов",
        unit: "кв.м.",
      },
      {
        code: "window_count",
        name: "PSPHC1_WindowCount",
        type: "int",
        caption: "Количество оконных проемов, всего",
        unit: "шт.",
      },
      {
        code: "window_common_count",
        name: "PSPHC1_WindowCommonCount",
        type: "int",
        caption: "в т.ч. в местах общего пользования",
        unit: "шт.",
      },
      {
        code: "window_area",
        name: "PSPHC1_WindowArea",
        type: "float",
        caption: "Площадь оконных проемов",
        unit: "кв.м.",
      },
      {
        code: "window_common_area",
        name: "PSPHC1_WindowCommonArea",
        type: "float",
        caption: "в т.ч. в местах общего пользования",
        unit: "кв.м.",
      },
      {
        code: "door_count",
        name: "PSPHC1_DoorCount",
        type: "int",
        caption: "Количество дверных проемов",
        unit: "шт.",
      },
      {
        code: "metal_door_count",
        name: "PSPHC1_MetalDoorCount",
        type: "int",
        caption: "в т.ч., металлические",
        unit: "шт.",
      },
      {
        code: "door_area",
        name: "PSPHC1_DoorArea",
        type: "float",
        caption: "Площадь дверных проемов",
        unit: "кв.м.",
      },
      {
        code: "metal_door_area",
        name: "PSPHC1_MetalDoorArea",
        type: "float",
        caption: "в т.ч., металлические",
        unit: "кв.м.",
      },
      {
        code: "glass_area",
        name: "PSPHC1_GlassArea",
        type: "float",
        caption: "Площадь остекления",
        unit: "кв.м.",
      },
      {
        code: "stool_area",
        name: "PSPHC1_StoolArea",
        type: "float",
        caption: "Площадь подоконных досок",
        unit: "кв.м.",
      },
      {
        code: "ironware_count",
        name: "PSPHC1_IronwareCount",
        type: "int",
        caption: "Скобяные изделия",
        unit: "компл.",
      },
      {
        code: "cellar_window_count",
        name: "PSPHC1_CellarWindowCount",
        type: "int",
        caption: "Количество подвальных окон",
        unit: "шт.",
      },
      {
        code: "cellar_window_area",
        name: "PSPHC1_CellarWindowArea",
        type: "float",
        caption: "Площадь подвальных окон",
        unit: "кв.м.",
      },
      {
        code: "roof_metal_area",
        name: "PSPHC1_RoofMetalArea",
        type: "float",
        caption: "Площадь кровли металлической",
        unit: "кв.м.",
      },
      {
        code: "roof_roll_area",
        name: "PSPHC1_RoofRollArea",
        type: "float",
        caption: "Площадь кровли из рулонных материалов",
        unit: "кв.м.",
      },
      {
        code: "roof_piece_area",
        name: "PSPHC1_RoofPieceArea",
        type: "float",
        caption: "Площадь кровли из штучных материалов",
        unit: "кв.м.",
      },
      {
        code: "roof_lathing_area",
        name: "PSPHC1_RoofLathingArea",
        type: "float",
        caption: "Площадь обрешетки кровли",
        unit: "кв.м.",
      },
      {
        code: "roof_rafter_count",
        name: "PSPHC1_RoofRafterCount",
        type: "int",
        caption: "Количество стропильных ног",
        unit: "шт.",
      },
      {
        code: "roof_metal_parapet_length",
        name: "PSPHC1_RoofMetalParapetLength",
        type: "float",
        caption: "Длина металлического открытия парапета",
        unit: "м.",
      },
      {
        code: "roof_vent_hood_count",
        name: "PSPHC1_RoofVentCapCount",
        type: "int",
        caption: "Количество колпаков на вентканалах",
        unit: "шт.",
      },
      {
        code: "roof_vent_count",
        name: "PSPHC1_RoofVentCount",
        type: "int",
        caption: "Количество вентканалов",
        unit: "шт.",
      },
      {
        code: "roof_cowl_count",
        name: "PSPHC1_RoofCowlCount",
        type: "int",
        caption: "Количество флюгарок на канализационных стояках",
        unit: "шт.",
      },
      {
        code: "roof_manhole_count",
        name: "PSPHC1_RoofManHoleCount",
        type: "int",
        caption: "Количество лазов на кровлю",
        unit: "шт.",
      },
      {
        code: "roof_exit_count",
        name: "PSPHC1_RoofExitCount",
        type: "int",
        caption: "Количество выходов на чердак",
        unit: "шт.",
      },
      {
        code: "roof_airhole_count",
        name: "PSPHC1_RoofAirHoleCount",
        type: "int",
        caption: "Количество продухов на чердаке",
        unit: "шт.",
      },
      {
        code: "roof_abatjour_count",
        name: "PSPHC1_RoofPeakCount",
        type: "int",
        caption: "Количество козырьков",
        unit: "шт.",
      },
      {
        code: "roof_abatjour_area",
        name: "PSPHC1_RoofPeakArea",
        type: "float",
        caption: "Площадь козырьков",
        unit: "кв.м.",
      },
      {
        code: "roof_gutter_length",
        name: "PSPHC1_RoofGutterLength",
        type: "float",
        caption: "Желоба",
        unit: "м.",
      },
      {
        code: "roof_downpipe_count",
        name: "PSPHC1_RoofDrainPipeCount",
        type: "int",
        caption: "Количество водосточных труб",
        unit: "шт.",
      },
      {
        code: "roof_downpipe_length",
        name: "PSPHC1_RoofDrainPipeLength",
        type: "float",
        caption: "Водосточные трубы",
        unit: "м.",
      },
      {
        code: "roof_cornice_length",
        name: "PSPHC1_RoofCorniceLength",
        type: "float",
        caption: "Свесы",
        unit: "м.",
      },
      {
        code: "roof_drainage_pipe_length",
        name: "PSPHC1_RoofLiftingPipeLength",
        type: "float",
        caption: "Водоотводящие стояки",
        unit: "м.",
      },
      {
        code: "roof_drainage_gutter_count",
        name: "PSPHC1_RoofChuteCount",
        type: "int",
        caption: "Водоотводящие лотки и отводы от здания",
        unit: "шт.",
      },
      {
        code: "roof_safety_barrier_length",
        name: "PSPHC1_RoofSafetyGratingLength",
        type: "float",
        caption: "Защитные ограждения",
        unit: "м.",
      },
      {
        code: "internal_glue_paint_area",
        name: "PSPHC2_IntDecGluePaintArea",
        type: "float",
        caption: "Площадь стен для клеевой окраски мест общего пользования",
        unit: "кв.м.",
      },
      {
        code: "internal_oil_paint_area",
        name: "PSPHC2_IntDecOilPaintArea",
        type: "float",
        caption: "Площадь стен для масляной окраски мест общего пользования",
        unit: "кв.м.",
      },
      {
        code: "internal_other_area",
        name: "PSPHC2_IntDecOtherArea",
        type: "float",
        caption: "Площадь других поверхностей в местах общего пользования",
        unit: "кв.м.",
      },
      {
        code: "internal_heat_center_wall_area",
        name: "PSPHC2_IndDecHeatingCenterWallArea",
        type: "float",
        caption: "Площадь стен в теплоцентрах",
        unit: "кв.м.",
      },
      {
        code: "internal_pipe_area",
        name: "PSPHC2_IntDecPipeArea",
        type: "float",
        caption: "Площадь поверхности труб",
        unit: "кв.м.",
      },
      {
        code: "internal_radiator_area",
        name: "PSPHC2_IntDecRadiatorArea",
        type: "float",
        caption: "Площадь поверхности радиаторов в местах общего пользования",
        unit: "кв.м.",
      },
      {
        code: "internal_stairway_grating_area",
        name: "PSPHC2_IntDecStairsGratingArea",
        type: "float",
        caption: "Площадь решеток на лестничных маршах",
        unit: "кв.м.",
      },
      {
        code: "internal_window_grating_area",
        name: "PSPHC2_IntDecWindowGratingArea",
        type: "float",
        caption: "Площадь решеток оконных ограждений",
        unit: "кв.м.",
      },
      {
        code: "internal_lift_grating_area",
        name: "PSPHC2_IntDecLiftGratingArea",
        type: "float",
        caption: "Площадь сетки шахт лифтов",
        unit: "кв.м.",
      },
      {
        code: "internal_mailbox_area",
        name: "PSPHC2_IntDecMailBoxArea",
        type: "float",
        caption: "Площадь почтовых ящиков ",
        unit: "кв.м.",
      },
      {
        code: "internal_stairway_internal_area",
        name: "PSPHC2_IntDecStairsInternalArea",
        type: "float",
        caption: "Площадь торцов на лестничных маршах",
        unit: "кв.м.",
      },
      {
        code: "internal_stairway_bottom_area",
        name: "PSPHC2_IntDecStairsButtArea",
        type: "float",
        caption: "Площадь нижней поверхности лестничных маршей",
        unit: "кв.м.",
      },
      {
        code: "front_area_total",
        name: "PSPHC2_FrontArea",
        type: "float",
        caption: "Площадь фасада, всего",
        unit: "кв.м.",
      },
      {
        code: "front_area_facial",
        name: "PSPHC2_FrontFacialArea",
        type: "float",
        caption: "лицевой фасад",
        unit: "кв.м.",
      },
      {
        code: "front_area_yard",
        name: "PSPHC2_FrontYardArea",
        type: "float",
        caption: "дворовый фасад",
        unit: "кв.м.",
      },
      {
        code: "front_area_butt",
        name: "PSPHC2_FrontButtArea",
        type: "float",
        caption: "торцовая часть",
        unit: "кв.м.",
      },
      {
        code: "external_plaster_area_total",
        name: "PSPHC2_ExtDecPlasterArea",
        type: "float",
        caption: "Площадь штукатурки, всего",
        unit: "кв.м.",
      },
      {
        code: "external_plaster_area_facial",
        name: "PSPHC2_ExtDecFacialPlasterArea",
        type: "float",
        caption: "лицевой фасад",
        unit: "кв.м.",
      },
      {
        code: "external_plaster_area_yard",
        name: "PSPHC2_ExtDecYardPlasterArea",
        type: "float",
        caption: "дворовый фасад",
        unit: "кв.м.",
      },
      {
        code: "external_plaster_area_butt",
        name: "PSPHC2_ExtDecButtPlasterArea",
        type: "float",
        caption: "торцовая часть",
        unit: "кв.м.",
      },
      {
        code: "external_coating_area_total",
        name: "PSPHC2_ExtDecCoatingArea",
        type: "float",
        caption: "Площадь облицовки, всего",
        unit: "кв.м.",
      },
      {
        code: "external_coating_area_facial",
        name: "PSPHC2_ExtDecFacialCoatingArea",
        type: "float",
        caption: "лицевой фасад",
        unit: "кв.м.",
      },
      {
        code: "external_coating_area_yard",
        name: "PSPHC2_ExtDecYardCoatingArea",
        type: "float",
        caption: "дворовый фасад",
        unit: "кв.м.",
      },
      {
        code: "external_coating_area_butt",
        name: "PSPHC2_ExtDecButtCoatingArea",
        type: "float",
        caption: "торцовая часть",
        unit: "кв.м.",
      },
      {
        code: "external_texture_area_total",
        name: "PSPHC2_ExtDecTextureArea",
        type: "float",
        caption: "Фактурный и окрасочные слои, всего",
        unit: "кв.м.",
      },
      {
        code: "external_texture_area_facial",
        name: "PSPHC2_ExtDecFacialTextureArea",
        type: "float",
        caption: "лицевой фасад",
        unit: "кв.м.",
      },
      {
        code: "external_texture_area_yard",
        name: "PSPHC2_ExtDecYardTextureArea",
        type: "float",
        caption: "дворовый фасад",
        unit: "кв.м.",
      },
      {
        code: "external_texture_area_butt",
        name: "PSPHC2_ExtDecButtTextureArea",
        type: "float",
        caption: "торцовая часть",
        unit: "кв.м.",
      },
      {
        code: "external_balcony_count",
        name: "PSPHC2_ExtDecBalconyCount",
        type: "int",
        caption: "Балконы",
        unit: "шт.",
      },
      {
        code: "external_balcony_area",
        name: "PSPHC2_ExtDecBalconyArea",
        type: "float",
        caption: "Площадь балконов",
        unit: "кв. м.",
      },
      {
        code: "external_lodge_count",
        name: "PSPHC2_ExtDecLodgeCount",
        type: "int",
        caption: "Лоджии",
        unit: "шт.",
      },
      {
        code: "external_lodge_area",
        name: "PSPHC2_ExtDecLodgeArea",
        type: "float",
        caption: "Площадь лоджий",
        unit: "кв. м.",
      },
      {
        code: "external_oriel_count",
        name: "PSPHC2_ExtDecOrielCount",
        type: "int",
        caption: "Эркеры",
        unit: "шт.",
      },
      {
        code: "external_porch_count",
        name: "PSPHC2_ExtDecPorchCount",
        type: "int",
        caption: "Крыльца",
        unit: "шт.",
      },
      {
        code: "external_metal_covering_area",
        name: "PSPHC2_ExtDecMetalCoveringArea",
        type: "float",
        caption: "Металлические покрытия на выступающих частях стен",
        unit: "кв.м.",
      },
      {
        code: "external_parapet_length",
        name: "PSPHC2_ExtDecParapetLength",
        type: "float",
        caption: "Парапеты",
        unit: "м.",
      },
      {
        code: "external_cornice_length",
        name: "PSPHC2_ExtDecCorniceLength",
        type: "float",
        caption: "Карнизы",
        unit: "м.",
      },
      {
        code: "external_belt_length",
        name: "PSPHC2_ExtDecBeltLength",
        type: "float",
        caption: "Пояса",
        unit: "м.",
      },
      {
        code: "external_draught_length",
        name: "PSPHC2_ExtDecDraughtLength",
        type: "float",
        caption: "Тяги",
        unit: "м.",
      },
      {
        code: "external_window_cover_length",
        name: "PSPHC2_ExtDecWindowCoverLength",
        type: "float",
        caption: "Окрытия окон",
        unit: "м.",
      },
      {
        code: "external_enclosure_length",
        name: "PSPHC2_ExtDecEnclosureLength",
        type: "float",
        caption: "Ограждения",
        unit: "м.",
      },
      {
        code: "external_wall_joint_length",
        name: "PSPHC2_ExtDecWallJointLength",
        type: "float",
        caption: "Длина стыков стеновых панелей",
        unit: "м.",
      },
      {
        code: "heating_length",
        name: "PSPHC2_HeatingLength",
        type: "float",
        caption: "Длина разводящей сети",
        unit: "м.",
      },
      {
        code: "heating_riser_pipe_count",
        name: "PSPHC2_HeatingRiserPipeCount",
        type: "int",
        caption: "Количество стояков",
        unit: "шт.",
      },
      {
        code: "heating_cellar_riser_pipe_length",
        name: "PSPHC2_HeatingCellarRiserPipeLength",
        type: "float",
        caption: "Длина стояков в подвалах",
        unit: "м.",
      },
      {
        code: "heating_flat_riser_pipe_length",
        name: "PSPHC2_HeatingFlatRiserPipeLength",
        type: "float",
        caption: "Длина стояков в квартирах",
        unit: "м.",
      },
      {
        code: "heating_flat_heating_length",
        name: "PSPHC2_HeatingFlatHeatingLength",
        type: "float",
        caption: "Длина разводки в квартирах",
        unit: "м.",
      },
      {
        code: "heating_stairway_radiator_count",
        name: "PSPHC2_HeatingStairsRadiatorCount",
        type: "int",
        caption: "Количество радиаторов на лестничных клетках",
        unit: "шт.",
      },
      {
        code: "heating_flat_radiator_count",
        name: "PSPHC2_HeatingFlatRadiatorCount",
        type: "int",
        caption: "Количество радиаторов в квартирах",
        unit: "шт.",
      },
      {
        code: "heating_armature_count",
        name: "PSPHC2_HeatingArmatureCount",
        type: "int",
        caption: "Запорно-регулирующая арматура",
        unit: "шт.",
      },
      {
        code: "heating_insulation_area",
        name: "PSPHC2_HeatingInsulationArea",
        type: "float",
        caption: "Теплоизоляция",
        unit: "кв.м.",
      },
      {
        code: "heating_steel_heater_count",
        name: "PSPHC2_HeatingSteelHeaterCount",
        type: "int",
        caption: "Калориферы стальные",
        unit: "шт.",
      },
      {
        code: "heating_convector_count",
        name: "PSPHC2_HeatingConvectorCount",
        type: "int",
        caption: "Конвекторы",
        unit: "шт.",
      },
      {
        code: "heating_catch_count",
        name: "PSPHC2_HeatingCatchCount",
        type: "int",
        caption: "Задвижки",
        unit: "шт.",
      },
      {
        code: "heating_valve_count",
        name: "PSPHC2_HeatingValveCount",
        type: "int",
        caption: "Вентили",
        unit: "шт.",
      },
      {
        code: "heating_threewaycock_count",
        name: "PSPHC2_HeatingThreeWayCockCount",
        type: "int",
        caption: "Трехходовые краны",
        unit: "шт.",
      },
      {
        code: "heating_elevator_count",
        name: "PSPHC2_HeatingElevatorCount",
        type: "int",
        caption: "Элеваторы",
        unit: "шт.",
      },
      {
        code: "heating_box_count",
        name: "PSPHC2_HeatingBoxCount",
        type: "int",
        caption: "Короба",
        unit: "шт.",
      },
      {
        code: "heating_center_count",
        name: "PSPHC2_HeatingCenterCount",
        type: "int",
        caption: "Количество теплоцентров",
        unit: "шт.",
      },
      {
        code: "cold_water_length",
        name: "PSPHC2_ColdWaterLength",
        type: "float",
        caption: "Длина разводящей сети",
        unit: "м.",
      },
      {
        code: "cold_water_riser_pipe_count",
        name: "PSPHC2_ColdWaterRiserPipeCount",
        type: "int",
        caption: "Количество стояков",
        unit: "шт.",
      },
      {
        code: "cold_water_cellar_riser_pipe_length",
        name: "PSPHC2_ColdWaterCellarRiserPipeLength",
        type: "float",
        caption: "Длина стояков в подвалах",
        unit: "м.",
      },
      {
        code: "cold_water_flat_riser_pipe_length",
        name: "PSPHC2_ColdWaterFlatRiserPipeLength",
        type: "float",
        caption: "Длина стояков в квартирах",
        unit: "м.",
      },
      {
        code: "cold_water_flat_length",
        name: "PSPHC2_ColdWaterFlatLength",
        type: "float",
        caption: "Длина разводки в квартирах",
        unit: "м.",
      },
      {
        code: "cold_water_brass_valve_count",
        name: "PSPHC2_ColdWaterBrassValveCount",
        type: "int",
        caption: "Вентили латунные",
        unit: "шт.",
      },
      {
        code: "cold_water_water_meter_count",
        name: "PSPHC2_ColdWaterWaterMeterCount",
        type: "int",
        caption: "Количество водомерных узлов",
        unit: "шт.",
      },
      {
        code: "cold_water_cellar_valve_count",
        name: "PSPHC2_ColdWaterCellarValveCount",
        type: "int",
        caption: "Количество вентилей в подвалах",
        unit: "шт.",
      },
      {
        code: "cold_water_ball_valve_count",
        name: "PSPHC2_ColdWaterBallValveCount",
        type: "int",
        caption: "Количество шаровых кранов в подвалах",
        unit: "шт.",
      },
      {
        code: "sewerage_cellar_pipe_length",
        name: "PSPHC2_SewerageCellarPipeLength",
        type: "float",
        caption: "Длина канализационных труб в подвалах",
        unit: "м.",
      },
      {
        code: "sewerage_cellar_riser_pipe_length",
        name: "PSPHC2_SewerageCellarRiserPipeLength",
        type: "float",
        caption: "Длина канализационных стояков в подвалах",
        unit: "м.",
      },
      {
        code: "sewerage_riser_pipe_count",
        name: "PSPHC2_SewerageRiserPipeCount",
        type: "int",
        caption: "Количество стояков",
        unit: "шт.",
      },
      {
        code: "sewerage_riser_pipe_length",
        name: "PSPHC2_SewerageRiserPipeLength",
        type: "float",
        caption: "Длина стояков",
        unit: "м.",
      },
      {
        code: "sewerage_revision_cover_count",
        name: "PSPHC2_SewerageRevisionCoverCount",
        type: "int",
        caption: "Количество крышек ревизий",
        unit: "шт.",
      },
      {
        code: "hotwater_length",
        name: "PSPHC2_HotWaterLength",
        type: "float",
        caption: "Длина разводящей сети",
        unit: "м.",
      },
      {
        code: "hotwater_cellar_riser_pipe_length",
        name: "PSPHC2_HotWaterCellarRiserPipeLength",
        type: "float",
        caption: "Длина стояков в подвалах",
        unit: "м.",
      },
      {
        code: "hotwater_flat_riser_pipe_length",
        name: "PSPHC2_HotWaterFlatRiserPipeLength",
        type: "float",
        caption: "Длина стояков в квартирах",
        unit: "м.",
      },
      {
        code: "hotwater_riser_pipe_count",
        name: "PSPHC2_HotWaterRiserPipeCount",
        type: "int",
        caption: "Количество стояков",
        unit: "шт.",
      },
      {
        code: "hotwater_flat_length",
        name: "PSPHC2_HotWaterFlatLength",
        type: "float",
        caption: "Длина разводки в квартирах",
        unit: "м.",
      },
      {
        code: "hotwater_catch_count",
        name: "PSPHC2_HotWaterCatchCount",
        type: "int",
        caption: "Количество задвижек",
        unit: "шт.",
      },
      {
        code: "hotwater_cellar_valve_count",
        name: "PSPHC2_HotWaterCellarValveCount",
        type: "int",
        caption: "Количество вентилей в подвалах",
        unit: "шт.",
      },
      {
        code: "hotwater_cellar_plug_valve_count",
        name: "PSPHC2_HotWaterCellarPlugValveCount",
        type: "int",
        caption: "Количество пробковых кранов в подвалах",
        unit: "шт.",
      },
      {
        code: "hotwater_other_count",
        name: "PSPHC2_HotWaterOtherCount",
        type: "int",
        caption: "Прочие",
        unit: "шт.",
      },
      {
        code: "electricity_entry_switch_count",
        name: "PSPHC3_ElectricSupplyEntrySwitchCount",
        type: "int",
        caption: "Вводно-распределительное устройство",
        unit: "шт.",
      },
      {
        code: "electricity_group_panel_count",
        name: "PSPHC3_ElectricSupplyGroupPanelCount",
        type: "int",
        caption: "Количество групповых щитков в подвале и на л/к",
        unit: "шт.",
      },
      {
        code: "electricity_power_panel_count",
        name: "PSPHC3_ElectricSupplyPowerPanelCount",
        type: "int",
        caption: "Количество силовых щитов",
        unit: "шт.",
      },
      {
        code: "electricity_switch_panel_count",
        name: "PSPHC3_ElectricSupplySwitchPanelCount",
        type: "int",
        caption: "Количество распределительных щитов",
        unit: "шт.",
      },
      {
        code: "electricity_common_light_length",
        name: "PSPHC3_ElectricSupplyMunicipalNetworkLength",
        type: "float",
        caption: "Длина сетей коммунального освещения",
        unit: "м.",
      },
      {
        code: "electricity_lift_power_length",
        name: "PSPHC3_ElectricSupplyLiftNetworkLength",
        type: "float",
        caption: "Длина сетей питания лифтов и электронасосов",
        unit: "м.",
      },
      {
        code: "electricity_number_plate_count",
        name: "PSPHC3_ElectricSupplyNumberPlateCount",
        type: "int",
        caption: "Количество номерных знаков",
        unit: "шт.",
      },
      {
        code: "electricity_daylight_lamp_count",
        name: "PSPHC3_ElectricSupplyDayLightLampCount",
        type: "int",
        caption: "Количество светильников дневного света",
        unit: "шт.",
      },
      {
        code: "electricity_incandescent_lamp_count",
        name: "PSPHC3_ElectricSupplyIncandescentLampCount",
        type: "int",
        caption: "Количество светильников с лампами накаливания",
        unit: "шт.",
      },
      {
        code: "electricity_arc_discharge_lamp_count",
        name: "PSPHC3_ElectricSupplyArcDischargeLampCount",
        type: "int",
        caption: "Количество светильников с лампами ДРЛ",
        unit: "шт.",
      },
      {
        code: "electricity_switch_count",
        name: "PSPHC3_ElectricSupplySwitchCount",
        type: "int",
        caption: "Количество выключателей",
        unit: "шт.",
      },
      {
        code: "electricity_meter_count",
        name: "PSPHC3_ElectricSupplyMeterCount",
        type: "int",
        caption: "Количество счетчиков, всего",
        unit: "шт.",
      },
      {
        code: "electricity_doublerate_meter_count",
        name: "PSPHC3_ElectricSupplyDoubleRateMeterCount",
        type: "int",
        caption: "в т.ч. двухтарифных",
        unit: "шт.",
      },
      {
        code: "",
        name: "PSPHC3_RefugeArea",
        type: "float",
        caption: "Площадь убежищ",
        unit: "кв.м.",
      },
      {
        code: "refuge_area",
        name: "PSPHC3_RefugeArea",
        type: "float",
        caption: "Площадь убежищ",
        unit: "кв.м.",
      },
      {
        code: "cellar_area",
        name: "PSPHC3_CellarArea",
        type: "float",
        caption: "Площадь подвалов",
        unit: "кв.м.",
      },
      {
        code: "refuge_metall_door_count",
        name: "PSPHC3_RefugeMetallCoorCount",
        type: "int",
        caption: "Количество металлических дверей в убежища",
        unit: "шт.",
      },
      {
        code: "lift_working_from_date",
        name: "PSPHC3_LiftExploitationFrom",
        type: "string",
        caption: "Год ввода лифтов в эксплуатацию",
        size: "4",
        unit: "год",
      },
      {
        code: "lift_reconstruction_date",
        name: "PSPHC3_LiftReconstructionDate",
        type: "string",
        caption: "Год реконструкции",
        size: "4",
        unit: "год",
      },
      {
        code: "lift_modernization_date",
        name: "PSPHC3_LiftModernisationDate",
        type: "string",
        caption: "Год модернизации",
        size: "4",
        unit: "год",
      },
      {
        code: "refuse_chute_shaft_count",
        name: "PSPHC3_RefuseChuteShaftCount",
        type: "int",
        caption: "Количество стволов",
        unit: "шт.",
      },
      {
        code: "refuse_chute_charging_valve_count",
        name: "PSPHC3_RefuseChuteChargingValveCount",
        type: "int",
        caption: "Количество приемо-загрузочных клапанов",
        unit: "шт.",
      },
      {
        code: "refuse_chute_chamber_area",
        name: "PSPHC3_RefuseChuteChamberArea",
        type: "float",
        caption: "Площадь мусороприемных камер",
        unit: "кв.м.",
      },
      {
        code: "paved_cover_area",
        name: "PSPHC3_PavedArea",
        type: "float",
        caption: "Покрытия замощенные",
        unit: "кв.м.",
      },
      {
        code: "stairway_sing_count",
        name: "PSPHC3_StairsSingPostCount",
        type: "int",
        caption: "Количество лестничных указателей",
        unit: "шт.",
      },
      {
        code: "bench_count",
        name: "PSPHC3_BenchCount",
        type: "int",
        caption: "Количество скамеек",
        unit: "шт.",
      },
      {
        code: "lawn_enclosure_area",
        name: "PSPHC3_LawnEnclosureArea",
        type: "float",
        caption: "Ограждения газонов",
        unit: "кв.м.",
      },
      {
        code: "asphalt_cover_area",
        name: "PSPHC3_AsphaltConcreteArea",
        type: "float",
        caption: "Асфальтобетонные покрытия, всего",
        unit: "кв.м.",
      },
      {
        code: "asphalt_cover_yard_passage_area",
        name: "PSPHC3_AsphaltConcreteYardPassageArea",
        type: "float",
        caption: "внутридворовые проезды",
        unit: "кв.м.",
      },
      {
        code: "asphalt_cover_pavement_area",
        name: "PSPHC3_AsphaltConcretePavementArea",
        type: "float",
        caption: "тротуары",
        unit: "кв.м.",
      },
      {
        code: "asphalt_cover_other_area",
        name: "PSPHC3_AsphaltConcreteOtherArea",
        type: "float",
        caption: "прочие",
        unit: "кв.м.",
      },
      {
        code: "playground_boom_count",
        name: "PSPHC3_ChildishEquipmentBoomCount",
        type: "int",
        caption: "Бумы",
        unit: "шт.",
      },
      {
        code: "playground_house_count",
        name: "PSPHC3_ChildishEquipmentHouseCount",
        type: "int",
        caption: "Домики",
        unit: "шт.",
      },
      {
        code: "playground_swing_count",
        name: "PSPHC3_ChildishEquipmentSwingCount",
        type: "int",
        caption: "Качели",
        unit: "шт.",
      },
      {
        code: "playground_sandbox_count",
        name: "PSPHC3_ChildishEquipmentSandBoxCount",
        type: "int",
        caption: "Песочницы",
        unit: "шт.",
      },
      {
        code: "playground_bench_count",
        name: "PSPHC3_ChildishEquipmentBenchCount",
        type: "int",
        caption: "Скамейки",
        unit: "шт.",
      },
      {
        code: "playground_swedishwall_count",
        name: "PSPHC3_ChildishEquipmentSwedishWallCount",
        type: "int",
        caption: "Шведские стенки",
        unit: "шт.",
      },
      {
        code: "playground_lawn_enclosure_area",
        name: "PSPHC3_ChildishEquipmentLawnEnclosureArea",
        type: "float",
        caption: "Ограждение газонов детских площадок",
        unit: "кв.м.",
      },
      {
        code: "balance_value",
        name: "PSPH_BalanceValue",
        type: "float",
        caption: "Балансовая восстановительная стоимость",
        size: "12",
        unit: "руб.",
      },
    ];

    this.t_object = t_json; // JSON.parse(t_json);
  }

  getParameterData(code: string) {
    let result: Object | undefined;
    this.t_object.forEach((element:any) => {
      if (element["code"] === code) {
        result = element;
      }
    });

    if (result === undefined) {
      return this.t_object[0];
    } else {
      return result;
    }
  }
}
